version: '3'

services:
  dashboard:
    image: grafana/grafana
    ports:
      - 2121:3000
    depends_on:
      - database

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=garjobatko
      - MYSQL_DATABASE=wind
    volumes:
      - "./database/data/:/docker-entrypoint-initdb.d"
      - "./database/config:/etc/mysql/conf.d"